name: Simple Mirroring

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
      - 'main'
      - 'dev'

jobs:
  repository_validation:
    name: "Repository Validation"
    uses: ./.github/workflows/repository_validation.yml
    with:
      strict_mode: false

  push_to_mirror:
    name: "Mirror Repository"
    needs: [repository_validation]
    if: ${{ github.event_name == 'push' && github.actor != 'github-actions[bot]' && startsWith(github.repository, 'morgangch') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
